version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf        

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - "1025:1025"
        - "1080:1080"

  fpm:
    depends_on:
      - mailcatcher
    build: ./fpm
    restart: always
    ports: 
      - "9000:9000"
    volumes:
      - "./www:/var/www/html"
  nginx:
    depends_on:
      - db
      - redis
      - fpm
    image: nginx:latest
    volumes:
      - "./www:/var/www/html"
      - "./conf/site.conf:/etc/nginx/conf.d/default.conf"      
    links:
      - db
      - redis
      - fpm
    ports:
      - "80:80"
      - "443:443"
    restart: always

  phpmyadmin:
    depends_on:
      - db  
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions